### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by AdamAliRS** [bejayoharen/java-bells#10]
I work on a MMORPG private server based on Runescape. I have created my own framework which recieves and sends the needfull information to login (Could be found here https://github.com/AdamAliRS/Gielinor-Netty-Framework) I was researching about having voice chat ingame since its multiplayer. Real time conference for every clanchat (Which is for a clan, it's in the name). I was wondering if voice chat could be integrated for every clanchat, so every clan chat will run a new thread for the voicechat and then send the input to the people in the clanchat via the client. 

Since, there is no real API's for something like that, I came across this and was wondering if this would be right for what I want to do. Any help is appreciated.

**Comment by bejayoharen** [comment]
I don't really understand what you are asking. Perhaps the best thing is to download the library and look at the sample code to see if it suits your needs.
